package uk.gov.digital.ho.hocs.cms.domain.exception;

public enum LogEvent {
    DOCUMENT_NOT_FOUND,
    COMPLAINT_DOCUMENT_IDS_NOT_FOUND,
    DOCUMENT_COPY_FAILED,
    DOCUMENT_RETRIEVAL_FAILED,
    DOCUMENT_BYTE_CONVERSION_FAILED,
    SQL_EXCEPTION,
    COMPLAINANT_ID_INVALID,
    REPRESENTATIVE_ID_INVALID,
    CORRESPONDENT_EXTRACTION_FAILED,
    CASE_DATA_DESCRIPTION_EXTRACTION_FAILED,
    COMPENSATION_DATA_EXTRACTION_FAILED,
    RISK_ASSESSMENT_EXTRACTION_FAILED,
    CASE_LINKS_EXTRACTION_FAILED,
    RESPONSE_EXTRACTION_FAILED,
    MIGRATION_MESSAGE_FAILED,
    MIGRATION_DOCUMENT_FAILED
}
