name: 'Docker Build Tag'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag.yml@v3
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-cms-data-migrator'
    secrets: inherit
